### ISSUE TITLE
When user see login form, cloud icon has different style

### ISSUE THREAD

**Issue by parkhojeong** [lablup/backend.ai-webui#1011]
**Describe the bug**
When user see login form, cloud icon has different style

**To Reproduce**

Go to login
see error

**Screenshots**
![image](https://user-images.githubusercontent.com/34734102/120834378-e5bf7800-c59d-11eb-9ae7-33853acc4206.png)

**Comment by lizable** [comment]
First of all,
thank you so much for your attention to [Backend.AI-webui](https://github.com/lablup/backend.ai-webui/) project, @parkhojeong.
We'll check it ASAP.
Also, If you find any other issues or suggestions, please let us know via GitHub issue channel!
