### ISSUE TITLE
If click the cluster size slider, sessions slider's disabled is changed even if there's no available session resource.

### ISSUE THREAD

**Issue by Sujin-Kim1** [lablup/backend.ai-webui#1017]
**Describe the bug**
When I start a new session and there is no available resource, all items of custom allocation are disabled.
But, I clicked any inside of the session slider, then the session slider is activated.

**To Reproduce**
1. Click on the 'Start' button to start a new session.
2. If you have not enough resources, all items of custom allocation will be disabled.
3. But, if you click any inside of the session slider, then the session slider is activated.

**Expected behavior**
If I don't have enough cluster resources, the session slider should still be disabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/28584164/122711743-a5e6d900-d29d-11eb-879b-99bd3c2a8eae.png)
![image](https://user-images.githubusercontent.com/28584164/122711768-b39c5e80-d29d-11eb-9404-c9a01ad81e9f.png)

**Comment by lizable** [comment]
I guess it's originated from the internal min-max value limit in mwc library. We shall need to discuss certain scenarios when min-max value becomes equal. And if those scenarios seems often, then we should re-consider using slider UI as our resource allocation.

**Comment by inureyes** [comment]
Fixed with refactoring.
