### ISSUE TITLE
Add a new page into the new-session-dialog.

### ISSUE THREAD

**Issue by Sujin-Kim1** [lablup/backend.ai-webui#1107]
**Is your feature request related to a problem? Please describe.**
There is an opinion that the number of sessions and the size of clusters are confusing.
So, I recommend you add a new page within the `new-session-dialog` and put those options on the new page.

**Describe the solution you'd like**
Make the structure of `new-session-dialog` as follows.

> [1, 2 page]
>   - No change  
>  
> [3 page]
>   - Resource Group
>   - Resource allocation
>     - CPU
>     - RAM
>     - Shared Memory
>     - GPU
>     - **~~Sessions~~**
>   - Cluster mode
>   - Cluster size
>   - **~~Session owner~~**
> 
> **[4 page]**
>   - Advanced settings
>     - Session owner
>     - Sessions
>     - **`OMP_NUM_THREAD`*** (with information dialog)
>  
> [5 page]
>   - Existing page 4   
>   (Total resource allocation, mounted folder, configurations, ...)
> 

*`OMP_NUM_THREAD`   
Backend.AI pre-specifies the OMP_NUM_THREADS environment variable as the number of allocated CPU cores in order to ensure that legacy software accurately recognizes container-allocated CPU resources while ensuring optimal performance when working with multi-threading through OpenMP. The pytorch official performance tuning guide also informs that it is necessary to adjust the value of `OMP_NUM_THREAD` when performing parallel operations as follows. https://pytorch.org/tutorials/recipes/recipes/tuning_guide.html#utilize-openmp 

**Describe alternatives you've considered**
`OMP_NUM_THREAD` can actually be set in `Environment Variable` on page 1. I purposely added the `OMP_NUM_THREAD` option on page 4 because it seems likely that it often occurs when code for a distributed container environment is run on multiple cores within a single container. **But you can add it wherever you think it is better.**
**So if you have a better idea to add the `OMP_NUM_THREAD` option to a better place, don't hesitate to share your ideas.**

**Additional context**
You can save `OMP_NUM_THREAD` options like other environment variables on the first page.

**Comment by lizable** [comment]
Resolved via #1009.
