### ISSUE TITLE
Enhance design of folder-explorer-dialog

### ISSUE THREAD

**Issue by Sujin-Kim1** [lablup/backend.ai-webui#1109]
**Describe the solution you'd like**
It would be better to center the buttons on the top right, and remove the arrow on the left, or add padding.
![image](https://user-images.githubusercontent.com/28584164/130574636-99ee37a4-0ab6-4848-a473-b46dec1aa5c1.png)

**Describe alternatives you've considered**
If you have any ideas to make this dialog look better other than what I mentioned, feel free to try!

**Additional context**
Click the folder icon on the `Data & Storage` page, then you can see the `folder-explorer-dialog`. (You need to create the folder in advance to see it.)

**Comment by studioego** [comment]
First, I add one div css  position & left elements.
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/20002/165251876-cbb99dbb-3977-4902-85bc-47d7ea13af5d.png">

**Comment by studioego** [comment]
Second, add margin-left attribute
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/20002/165254764-2b6a7fbf-4840-4cb2-ac00-35e1aab937c4.png">
