### ISSUE TITLE
Connect file name and file icon

### ISSUE THREAD

**Issue by euni00** [lablup/backend.ai-webui#1115]
**Is your feature request related to a problem? Please describe.**
If we connect file name and file icon, it will be better to use.

![Backend ai_Issue](https://user-images.githubusercontent.com/82070770/131154158-f65f2239-7a76-4436-ab10-58d214654e8d.jpeg)

**Describe the solution you'd like**
Please connect file name(backendtutorial-folder) and file icon and add highlight font and underline on file name to see if you can click it.

**Describe alternatives you've considered**
If you have any ideas to make this dialog look better other than what I mentioned, feel free to try!

**Additional context**

**Comment by studioego** [comment]
In my opinion, Backend.ai's grid use `vaadin`.
So, It should be easily resolve the issue.
Example) 
https://cdn.vaadin.com/vaadin-elements/latest/vaadin-grid/demo/selection.html

**Comment by studioego** [comment]
Hmm... typescript's @material/mwc-icon-button don't support tooltip feature.
Currently, <mwc-tooltip> feature is  TBD
<mwc-tooltip>	https://github.com/material-components/material-components-web-components/issues/1499

So, That issue is holding......
