### ISSUE TITLE
vaadin-grid-list does not support template anymore

### ISSUE THREAD

**Issue by inureyes** [lablup/backend.ai-webui#1128]
**Describe the bug**
vaadin-grid-list does not support template anymore. So the items are not rendered.

**Comment by lizable** [comment]
@inureyes I guess this issue has been solved via #998 already.

**Comment by inureyes** [comment]
@lizable Let's check the left `template` part in our code.

**Comment by inureyes** [comment]
There are leftovers: 

backend-ai-scaling-group-list.ts
backend-ai-storage-list.ts

**Comment by inureyes** [comment]
backend-ai-storage-list.ts will be fixed when https://github.com/lablup/backend.ai-webui/pull/1490 is merged.

**Comment by inureyes** [comment]
It is resolved.
