### ISSUE TITLE
The graph of statistic page doesn't respond.

### ISSUE THREAD

**Issue by Sujin-Kim1** [lablup/backend.ai-webui#1147]
**Describe the bug**
The graph of statistic page doesn't respond even if I used resources and terminated sessions.

**To Reproduce**
1. Go to 'statistic' page after terminating sessions.
2. The graph doesn't change.

**Expected behavior**
Show the information on the amount of resources I used on the graph.

**Screenshots**
![image](https://user-images.githubusercontent.com/28584164/138223958-3c284404-6ee2-48fe-a200-a565b3b34d36.png)

**Comment by lizable** [comment]
@Sujin-Kim1 I guess this issue has been solved via this PR(#998). Could you close this issue if it works fine?
