### ISSUE TITLE
A wide blank is created when reducing the size of window.

### ISSUE THREAD

**Issue by Sujin-Kim1** [lablup/backend.ai-webui#1202]
**Describe the bug**
When the window size is reduced and converted to a mini menu, a wide blank is created.

**To Reproduce**
You can see this error on every page if you reduce the size of the window.

**Expected behavior**
When converted to mini-ui, only margins of an appropriate size should exist on both sides of the content. Get rid of the big blanks!

**Screenshots**
<img src="https://user-images.githubusercontent.com/28584164/150536411-009404de-34b4-48a0-b928-9371e2f6ad78.png" width=500/>

**Client:**
- OS: macOS Monterey 12.4
- Browser version: Chrome
- Python version: 3.9.9
- NodeJS version: 16.13.1

**Comment by studioego** [comment]
In my opinion, It needs to check the PR #1214 . 
If the issue confliction is changed, I'll request to review the PR #1214 
<img width="1946" alt="image" src="https://user-images.githubusercontent.com/20002/166182310-71df60c1-035d-402b-b00f-fa58a5dfec87.png">

**Comment by studioego** [comment]
Following the PR #1214 , I checked to remoe wide blank.

However, the PR #1214 , There are unnecessary code changes.

I'll refect the code and re-submit the PR and close PR #1214 

<img width="1946" alt="image" src="https://user-images.githubusercontent.com/20002/166182701-11734507-0946-48b5-a5aa-dabafc46876f.png">

**Comment by studioego** [comment]
As the PR https://github.com/lablup/backend.ai-webui/pull/1214 has already merged to the main branch. So, I close the issue.
