### ISSUE TITLE
Refactor `mwc-select` and `mwc-list-item` style definition to css variable

### ISSUE THREAD

**Issue by lizable** [lablup/backend.ai-webui#1207]
**Describe the bug**
문제가 발생하는 상황에 대한 요약 설명을 적어주세요.
If the dialog contains select UI that uses [`mwc-select`](https://github.com/material-components/material-web/tree/master/packages/select) and the list items exceed the height of the dialog, an undesired horizontal scrollbar appears.

**To Reproduce**
문제를 재현하기 위한 순서를 자세히 적어주세요:

**Expected behavior**
원래 기대했던 동작은 어떤 것인지 명확하게 적어주세요.
[`mwc-select` and corresponding `mwc-list-item`](https://github.com/material-components/material-web/tree/master/packages/select) supports css variable `--mdc-min-width` and `--mdc-max-width`, whch internally limits width of items in select menu, therefore css definition components that contains `mwc-select` that enabled `fixedMenuPosition` need to be changed.

We already solved this problem only for `backend-ai-session-launcher` component in #1206, therefore we need to apply this [css variable setting](https://github.com/lablup/backend.ai-webui/blob/2218164a4c63c30f38d47a6f00ab8d39125b4aff/src/components/backend-ai-session-launcher.ts#L560-L562) to every component that has select UI in the dialog.

**Screenshots**
Just take a screenshot in your clipboard or copy a picture file and paste it here (Ctrl+V/Cmd+V) so that GitHub automatically attach and insert it.
가능하다면, 문제 상황을 보여주는 스크린샷을 첨부해주세요.
클립보드에 스크린샷을 찍거나 이미지 파일을 복사해서 여기에 붙여넣으면(Ctrl+V/Cmd+V) GitHub이 자동으로 이곳에 첨부 및 삽입해줍니다.
![Screen Shot 2022-01-25 at 10 22 53 AM](https://user-images.githubusercontent.com/46954439/150904649-97b7587b-23f3-49d5-b761-32bf7b26cc23.png)

**Client:**
 - OS: [e.g. macOS 10.14, Windows 10 (1903)]
 - App version: [e.g. 19.08.3] (if you are using a GUI client app)
 - Browser version: [e.g. Chrome 76, Safari, Edge] (if you are using a GUI web console)
 - Python version: [e.g. 3.7.4] (if you are using the Python SDK)
 - NodeJS version: [e.g. 12.0] (if you are using the Javascript SDK)

**Server:**
 - OS: [e.g. Ubuntu 18.04, CentOS 7.6, macOS 10.14]
   - Output of `uname -a`: [e.g. `Linux node01 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`]
 - Backend.AI version: [e.g. 19.09.0]
 - Python version: [e.g. 3.6.8]
 - Installation method: [e.g. on-premise, using cloud.backend.ai service, used scripts/install-dev.sh]

**Additional context**
추가적으로 문제 상황을 설명할 수 있는 다른 맥락을 기술해주세요.

**Comment by studioego** [comment]
I'm trying to refactor it.

**Comment by studioego** [comment]
I checked some files that using mwc-select with mwc-list-item properties on web-ui's typescript files according to the  https://github.com/lablup/backend.ai-webui/pull/1206 contents.

```
➜  backend.ai-webui git:(fix/refactor_mwc_select_style_css) ✗ grep "mwc-select {" ./src/components/* -R
./src/components/backend-ai-credential-list.ts:        mwc-select {
./src/components/backend-ai-data-view.ts:        mwc-select {
./src/components/backend-ai-environment-list.ts:        mwc-select {
./src/components/backend-ai-general-styles.ts:    mwc-select {
./src/components/backend-ai-import-view.ts:        mwc-select {
./src/components/backend-ai-resource-group-list.ts:        mwc-select {
./src/components/backend-ai-resource-monitor.ts:        #scaling-group-select-box mwc-select {
./src/components/backend-ai-resource-monitor.ts:        mwc-select {
./src/components/backend-ai-session-launcher-legacy.ts:        mwc-select {
./src/components/backend-ai-session-launcher.ts:        mwc-select {
./src/components/backend-ai-settings-view.ts:        mwc-select {
./src/components/backend-ai-storage-list.ts:        backend-ai-dialog mwc-select {
./src/components/backend-ai-usage-list.ts:        mwc-select {
./src/components/backend-ai-usersettings-general-list.ts:        mwc-select {
./src/components/backend-ai-webui-styles.ts:    span.full_name, mwc-select {
./src/components/lablup-terms-of-service.ts:        mwc-select {
```
However, As I checked, Some `mwc-select` properties on CSS files may not need to be modified.

I think it will take time to check after modifying some files.

**Comment by studioego** [comment]
This is checking & working log.
1. ./src/components/backend-ai-session-launcher-legacy.ts: is ignore.
2. ./src/components/backend-ai-session-launcher.ts:  is already modified. 
other things are checking about widths and heights.

**Comment by studioego** [comment]
Hmm, I checked & modified some page's css `mwc-select` and `mwc-list-item` style  definition.
Below is my modified branch url .
https://github.com/lablup/backend.ai-webui/tree/fix/refactor_mwc_select_style_css

After committing it, I checked the difference between the main branch and my working branch.

I ignored the latest modifications of the main branch's `backend-ai-storage-list.ts` file and committed the modifications to my branch.

Therefore, it seems to be necessary to create a new branch and make additional modifications.

I need to check more ts files.
Below need to check some ts file lists.
 * backend-ai-data-view.ts
 * backend-ai-import-view.ts
 * backend-ai-webui-styles.ts

**Comment by studioego** [comment]
Now, I almost finished resolving the issue. But,  I need to check  broken pages.

**Comment by studioego** [comment]
Finally, I submitted to fix the issue files. However, there may be cases where the issue's CSS modifications are omitted.
@lizable  If you have time, lease check it slowly.
Take care!

**Comment by studioego** [comment]
It merged. So, I close the issue.
