### ISSUE TITLE
App crashes on network drive (UNC Path) in Windows

### ISSUE THREAD

**Issue by appleparan** [lablup/backend.ai-webui#1220]
**Describe the bug**
Copy GUI client app files to network drive and launch it, then the app is crashed.

**To Reproduce**

To test by mapping local folder to driver letter

1. Let app files are extracted in `D:\somedirectory`
2. Map drive letter `X` with `somedirectory`
    ```
    net use x: \\localhost\d$somedirectory
    ```
3. Launch app in `X:`

**Expected behavior**
App launched normally

**Client:**
 - OS: Windows 10 20H2
 - App version: 21.09.3 (if you are using a GUI client app)

**Additional context**
Judging by [this issue](https://github.com/electron/electron/issues/25618), it appears to be related to Chromium's sandbox mode. I'm not sure whether this is a solvable problem.

**Comment by adrysn** [comment]
Thank you for your report! As you have said, this issue seems to be related to the upstream issue of Chrome's sandboxing and general Electron apps. Since there is nothing we can do in this repository, I'll close this.
