### ISSUE TITLE
Three or more platform tags are not recognizable

### ISSUE THREAD

**Issue by adrysn** [lablup/backend.ai-webui#1242]
Kernel image's tag is composed of `<version-tag>-<platform-tag-1>-<platform-tag-2>-<platform-tag-3>...`. When there are more than three platform tags, users cannot see the tags and this may result in displaying the exact same image items in the list even for two different images.

For example, consider there are two different kernel images with different length of platform tags:
```bash
lablup/python-kaldi:2.0-py27-cuda10.0
lablup/python-kaldi:2.0-py27-cuda10.0-mlflow1.7
```

In Web-UI, the above two images are displayed exactly the same. It seems like Web-UI ignores three or more platform tags:
<img width="827" alt="image" src="https://user-images.githubusercontent.com/7539358/155079000-b7a47965-9bfd-40a3-9240-e98cdb7df734.png">

It would be hard to display every platform tags with arbitrary length, but we need to provide a way to discern two images with different platform tags.

**Comment by lizable** [comment]
@adrysn Is there any chance of incrementing "tags" more than three, such as "lablup/python-kaldi:2.0-py27-cuda10.0-mlflow1.7-01" or "lablup/python-kaldi:2.0-py27-cuda10.0-mlflow1.7-01-arm64"?

**Comment by adrysn** [comment]
I think so. I suggest adding a region that displays the entire image `<name:tag>` string as-is in.

**Comment by lizable** [comment]
@inureyes 
To my knowledge, for providing a better user experience, we limited tags to at most 3. But, It's true that we also allow adding tags more than that, so I think we should reconsider the layout of kernel image in the dropdown or may just restrict it.
IMHO, It would be great to support adding tags, even if we change the user interface.

**Comment by adrysn** [comment]
Done by https://github.com/lablup/backend.ai-webui/pull/1614
