### ISSUE TITLE
Enable terminal app for a batch-type session

### ISSUE THREAD

**Issue by adrysn** [lablup/backend.ai-webui#1243]
A batch-type session does not allow users to access apps like terminal, Jupyter, etc. The icon is disabled by default as below.

<img width="722" alt="image" src="https://user-images.githubusercontent.com/7539358/155910817-4ead1584-0816-4a28-ba87-c1c4fdb398f1.png">

Even for a batch-type session, there might be a need to monitor and debug the running jobs by accessing the terminal of that session. So, I propose to enable at least the terminal app button for better usability.

**Comment by inureyes** [comment]
Implemented. (single-line commit with discussion so I merged the PR directly into local main.)
