### ISSUE TITLE
GPU value is broken when creating a cluster session (N=3) with 0.3 fGPU

### ISSUE THREAD

**Issue by adrysn** [lablup/backend.ai-webui#1249]
GPU value is broken when creating a cluster session (N=3) with 0.3 fGPU.

## Steps to reproduce
- Create a cluster compute session with a size of 3. It doesn't matter the node type: single-node or multi-node.
- In the last page of the session launch dialog, you will notice the broken GPU unit: 0.999999999....

<img width="430" alt="image" src="https://user-images.githubusercontent.com/7539358/156499480-22e210ac-6a3d-49c4-ab49-cb3c2d2d880d.png">

**Comment by studioego** [comment]
I have a question. 
I installed Backend.ai using `--enable-cuda` option. (Linux[Fedora Core 35] + Nvidia GTX 1650 Ti Laptop)
So, I can install Tensorflow and Pytorch using Nvidia GPU module. 
However, I only select 0 and 1 GPU selections.  It don't able to set to decimal point in GPU setting. sucn as 0.1, 0.3, etc.
How to set to decimal point in GPU setting?
![image](https://user-images.githubusercontent.com/20002/164484823-2294ea02-e977-4d32-a864-06a301db26c6.png)
