### ISSUE TITLE
Display multi-level namespace correctly to provide enough information to distinguish images with the same name but in different namespaces

### ISSUE THREAD

**Issue by adrysn** [lablup/backend.ai-webui#1255]
It would be best to explain this issue with an example.

Recently, I tried to integrate the [GitLab container registry](https://docs.gitlab.com/ee/administration/packages/container_registry.html), and it was successful. An image in a GitLab's container registry follows the naming convention as `<registry URL>/<namespace>/<project>/<image>`, for example, something like `10.20.30.10:7055/root/test/r-base:4.1`.

This image was displayed in Web-UI like below:
![image](https://user-images.githubusercontent.com/7539358/158017365-85c50827-da60-44c7-b48a-81fc4917ef1d.png)

We see that there is only one visualized tag, `root`, and this lets users know that the image belongs to a user `root`, but failed to give what project it came from. This may be a minor issue, but it will confuse users, especially for the following scenario:
- There are two images with the same user and name, but with a different project.
  - `10.20.30.10:7055/root/test1/r-base:4.1`
  - `10.20.30.10:7055/root/test2/r-base:4.1`
- In this case, there will be two same r-base (root) images in the environment list, but a user cannot tell what is the difference.

I think we need a way to distinguish the images with multi-level namespaces.

**Comment by studioego** [comment]
Excuse me, How can I check and test the issue?

**Comment by studioego** [comment]
It is already merged. So, Close the issue.
