### ISSUE TITLE
Show Scheduler Options using lablup shields component.

### ISSUE THREAD

**Issue by Sujin-Kim1** [lablup/backend.ai-webui#1263]
**Is your feature request related to a problem? Please describe.**
`Scheduler Options` column is not scrollable and its content is overflowed. For easier understanding and better design for users, it is recommended to render using `labup-shields`.
<img width="280" alt="image" src="https://user-images.githubusercontent.com/28584164/161688143-21a25cd4-7348-4d38-b827-cecd6b09b53e.png">

**Describe the solution you'd like**
Use `lablup-shields` like status column.
<img width="278" alt="image" src="https://user-images.githubusercontent.com/28584164/161688940-b5317605-3afc-42ed-85db-ad1963893258.png">

**Comment by Sujin-Kim1** [comment]
Duplicated issue.

**Comment by lizable** [comment]
duplicated in #1190.
