### ISSUE TITLE
style: make disable or remove the animation of buttons that do not trigger other events

### ISSUE THREAD

**Issue by Sujin-Kim1** [lablup/backend.ai-webui#1335]
**Is your feature request related to a problem? Please describe.**
Some buttons have an animation even though they don't trigger other events. So users can be confused about which buttons have effects.

**Describe the solution you'd like**
For buttons that do not trigger other events, you can respond as follows or in other ways.
- make disable
- remove the animation
- avoid turning into a pointer cursor when hovering buttons

**Additional context**
e.g ) In the notification panel under sidebar and owner column in data & folder page, they have an effect when hovering / clicking but they don't trigger other events.

**Comment by jangjichang** [comment]
I'll try to solve the issue.
