### ISSUE TITLE
Don't show the modified Registries information after modify registry information 

### ISSUE THREAD

**Issue by studioego** [lablup/backend.ai-webui#1346]
**Describe the bug**
문제가 발생하는 상황에 대한 요약 설명을 적어주세요.
Don't show the modified Registries information after modify registry information 

**To Reproduce**
문제를 재현하기 위한 순서를 자세히 적어주세요:
1. Go to 'Environments' menu (needs Administration level)
2. Click on 'Registry' tab
3. Click modify Registry button 
4. Show Modify Registries popup, Try to modify registries information & save it
5. retry to Click modify Registry button 
6. See an error

**Expected behavior**
원래 기대했던 동작은 어떤 것인지 명확하게 적어주세요.

Don't show the registry information on Modify Registry tab

**Screenshots**
Just take a screenshot in your clipboard or copy a picture file and paste it here (Ctrl+V/Cmd+V) so that GitHub automatically attach and insert it.
가능하다면, 문제 상황을 보여주는 스크린샷을 첨부해주세요.
클립보드에 스크린샷을 찍거나 이미지 파일을 복사해서 여기에 붙여넣으면(Ctrl+V/Cmd+V) GitHub이 자동으로 이곳에 첨부 및 삽입해줍니다.

For the first time, Modify Registry information
<img width="463" alt="스크린샷 2022-07-05 오후 12 12 40" src="https://user-images.githubusercontent.com/20002/177250151-8ae43a27-70ef-428f-b558-8a6eb8fde752.png">

After modified Registry information, try to click and show Modify Registrty popup.
It shows that don't show the modified Registries information after modify registry information 
<img width="486" alt="스크린샷 2022-07-05 오후 12 12 56" src="https://user-images.githubusercontent.com/20002/177250159-7fbc23e1-3fd0-41a4-9d42-4fbb86bb861d.png">

https://user-images.githubusercontent.com/20002/177250248-9c87df78-693d-4c0c-b684-8eb70f13f2e2.mov

**Client:**
 - OS: macOS 12.4 
 - App version: [e.g. 19.08.3] (if you are using a GUI client app)
 - Browser version: Chrome 103.0.5060.53
 - Python version: 3.10.5
 - NodeJS version: 18.4

**Server:**
 - OS: macOS 12.4 
   - Output of `uname -a`: `Darwin seongdacBookPro.office.lablup 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64`
 - Backend.AI version: main
 - Python version: 3.10.5
 - Installation method: [ used scripts/install-dev.sh ]

**Additional context**
추가적으로 문제 상황을 설명할 수 있는 다른 맥락을 기술해주세요.

**Comment by lizable** [comment]
@studioego I think it's better to treat as another `good-first-issue`. How about unchecking all of the assignees, and letting new contributors can dig this issue?

**Comment by studioego** [comment]
> @studioego I think it's better to treat as another `good-first-issue`.

I added the `good first issue` tag on the issue.

>  How about unchecking all of the assignees, and letting new contributors dig this issue?

I agree. So, I unchecking all of the assignees.
