### ISSUE TITLE
Provide selecting agent on session creation in limited situation

### ISSUE THREAD

**Issue by lizable** [lablup/backend.ai-webui#1360]
**Is your feature request related to a problem? Please describe.**
기능 요청이 특정 문제에 연관된 것이라면 여기에 그 문제를 설명해주세요.

Although manager component has been already providing scheduling algorithms when there are multiple agents in a single resource-group, It would be great to provide the user interface for selecting available agents in session launcher on user demand.

**Describe the solution you'd like**
어떤 기능이 있으면 좋겠는지 자세히 설명해주세요.

> ⚠️ NOTE: This feature is available in certain situations below
> - The user can access a resource group with multiple agent nodes
> - There should be a toggle option for enabling/disabling this feature.

- [ ] Provide selective UI for resource group and associated agents
- [ ] (Optional) Show available resource for each agent in resource group

**Describe alternatives you've considered**
혹시 다른 대안들을 생각해본 적이 있다면 함께 적어주세요.

**Additional context**
기능 요청에 대해 보다 잘 이해할 수 있는 다른 맥락을 기술해주세요.

There's another client-side interface that already provides session creation with selected agent node.
Please refer to the code below: https://github.com/lablup/backend.ai/blob/dcb9bb5f8250a9733d6c68930df62bb4610f0a7a/src/ai/backend/client/cli/session.py#L118-L121

**Comment by yomybaby** [comment]
This is duplicated by https://github.com/lablup/backend.ai-webui/issues/2589 . I'll close this.
