### ISSUE TITLE
Use common functions and variables of `backend-ai-page`

### ISSUE THREAD

**Issue by lizable** [lablup/backend.ai-webui#1380]
**Is your feature request related to a problem? Please describe.**
기능 요청이 특정 문제에 연관된 것이라면 여기에 그 문제를 설명해주세요.
There are many duplicated functions that are used in many components, which work exactly the same or slightly differently per each component. It's better to rearrange certain functions into superclass([`backend-ai-page`](https://github.com/lablup/backend.ai-webui/tree/main/src/components/backend-ai-page.ts)).

**Describe the solution you'd like**
어떤 기능이 있으면 좋겠는지 자세히 설명해주세요.
Here's a guide for deduping scattered functions:
1. Find duplicated functions and variables used in multiple(more than one) components.
2. Rearrange the functions and variables found in step 1 to superclass component.
3. If there are any component-specific statements in the functions or variables, then use `override` keyword and override them to the component.

**Describe alternatives you've considered**
혹시 다른 대안들을 생각해본 적이 있다면 함께 적어주세요.

**Additional context**
기능 요청에 대해 보다 잘 이해할 수 있는 다른 맥락을 기술해주세요.

**Comment by yomybaby** [comment]
Closing this issue as it is no longer valid.
