### ISSUE TITLE
Increase the size, padding, margin of the dialogs

### ISSUE THREAD

**Issue by Sujin-Kim1** [lablup/backend.ai-webui#1452]
**Is your feature request related to a problem? Please describe.**
Overall, the dialog width and space between items are so narrow that it's hard to tell them apart. Let's increase the size and margin/padding of the dialogs.

**Describe the solution you'd like**
Increase margins and width for better readability.

**Comment by di-uni** [comment]
<img width="325" alt="image" src="https://user-images.githubusercontent.com/50884017/190062991-945982e2-9e2a-4771-a883-f90288f43bdb.png">
Do you mean the dialog like this? 
This looks not that narrow for me, so can you give some detailed examples and descriptions how to improve?

**Comment by Sujin-Kim1** [comment]
@di-uni  Yes that's right. 
1. **without margin**
  There are some fields without margin among components in some dialog as you posted it or like below.
     <img width="404" alt="image" src="https://user-images.githubusercontent.com/28584164/190083224-e6f8d3f6-715a-4984-ba7a-6b8ce54aaa83.png">
  -> Apply "consistent" margin.

2. **full-size field**
   Some fields are full-size without padding. 
    <img width="378" alt="image" src="https://user-images.githubusercontent.com/28584164/190085506-41c2e3fa-ec65-40a4-9edf-23e10de0c134.png">
    -> Apply "consistent" padding.

I hope that all padding and margin between fields used in the dialog are unified.

**Comment by inureyes** [comment]
Hmm...Now every margin/padding is same except session launcher which requires more information to setup and run on mobile.

**Comment by inureyes** [comment]
I checked every dialog and confirmed that they have same margin/padding, except session launcher.
