### ISSUE TITLE
The user who has the Korean username can not be created

### ISSUE THREAD

**Issue by xyloon** [lablup/backend.ai-webui#1453]
**Describe the bug**

The user who has the Korean username can not be created.
And no response. (No popup and No user created)
![image](https://user-images.githubusercontent.com/28333289/188140453-906c976e-931a-4ac8-a4a0-b07965abc6b9.png)

**To Reproduce**

Precondition : Admin login

Users -> Active -> (+ Create user button)

Insert user informaton with the English but "Username" have to be the Korean.

![image](https://user-images.githubusercontent.com/28333289/188141156-e2137ad8-9c8d-4955-a37f-3d17aa24ed12.png)

Then press the "+ CREATE USER"

After that.

No response.

**Expected behavior**

Error popup "No user who has Korean username could be created" 

OR

The user have be be created. 

**Screenshots**

![image](https://user-images.githubusercontent.com/28333289/188141549-7a7f7697-f018-497a-bf47-afe1701969f3.png)

**Client:**
 - OS: MACOS 12.5 and Windows 10
 - App version: 22.03.3
 - Browser version: Chrome browser 104.0.5112.101
 - Python version: [e.g. 3.7.4] (if you are using the Python SDK)
 - NodeJS version: [e.g. 12.0] (if you are using the Javascript SDK)

**Server:**
 - OS: Ubuntu 20.04
   - Output of `uname -a`: Linux Proxy 5.8.0-45-generic #51~20.04.1-Ubuntu SMP Tue Feb 23 13:46:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 - Backend.AI version: 22.03.10
 - Python version: 3.10.5
 - Installation method: Ansible
 
**Additional context**

**Comment by lizable** [comment]
Thx for reporting the error @xyloon!
The issue has been confirmed, and I get status code 400(Bad Request) when requesting user creation with a Korean username.
I'll fix this ASAP.

**Comment by inureyes** [comment]
It is fixed so I'll close the issue.
