### ISSUE TITLE
Enhance `building desktop app` github actions

### ISSUE THREAD

**Issue by mihilt** [lablup/backend.ai-webui#1462]
### Main idea

https://github.com/lablup/backend.ai-webui/blob/cc311ce1a66abda9a1b53bf4768aaa96352da2ec/.github/workflows/package.yml#L1-L38

I'm not sure because this project's release cycle is long and it only takes 12 seconds to install its all dependencies, so it may not be efficient. But I think caching these npm dependencies to use GitHub’s “cache action" can prevent wasting unnecessary resources and can make it faster.

Reference: [caching-dependencies-to-speed-up-workflows](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows)

**Comment by inureyes** [comment]
@mihilt After carefully evaluating the release data and differences in package dependencies for each version over the course of a year, I found that we update our package dependencies very frequently. Interestingly, none of the releases have the same package dependency metrics as their previous versions. Based on these findings, it seems that implementing caching might not be beneficial for us.
