### ISSUE TITLE
Let's add helper dialog and validation for endpoint

### ISSUE THREAD

**Issue by Sujin-Kim1** [lablup/backend.ai-webui#1468]
### Main idea

When trying to log in, many people have a hard time figuring out what to set the endpoint to.
So let's add the following to make endpoint configuration easier. 
- [ ] an icon button to the endpoint field
- [ ] add a dialog explaining which value is appropriate to set as the endpoint.
- [ ] add a validation (e.g. URL Starts with http:// or https://")

### Anything else?

ref: https://docs.backend.ai/en/latest/install/development-setup.html, https://github.com/lablup/backend.ai/blob/main/scripts/install-dev.sh#L904-L926

**Comment by jangjichang** [comment]
i will check this issue

**Comment by jangjichang** [comment]
@Sujin-Kim1 https://github.com/lablup/backend.ai-webui/pull/1470

**Comment by di-uni** [comment]
I will check this issue about icon and dialog!
