### ISSUE TITLE
Strange UI of mounted folders

### ISSUE THREAD

**Issue by Sujin-Kim1** [lablup/backend.ai-webui#1577]
### What Operating System(s) are you seeing this problem on?

macOS (Apple Silicon)

### Backend.AI version

a18238c

### Describe the bug

As the session and kernel table are divided, the mounted folder list of sessions shows the full info of `vfolder_host_permission`. Let's display only the mounted folder name list.
<img width="930" alt="image" src="https://user-images.githubusercontent.com/28584164/217997998-922bf79d-f61a-4c4b-b0b1-ab3f76d2751b.png">

### To Reproduce

Make a new session with mounting any folder.

### Expected Behavior

Display mounted folder name only.

**Comment by lizable** [comment]
Closing this issue since It's been resolved via [backend.ai#1034](https://github.com/lablup/backend.ai/pull/1034).
