### ISSUE TITLE
Let's add option to hide sharing virtual folder

### ISSUE THREAD

**Issue by lizable** [lablup/backend.ai-webui#1629]
### Main idea

There are certain situations that don't need sharing virtual folders (e.g. shortage of storage...)
For now, we've been providing sharing virtual folders as a default, but we can convert it as an "optional" feature.

**Comment by adrysn** [comment]
Let's hide the share/manage-share buttons from each folder item if there is no `invite-others` (or Invite user folder) in the host permission.
