### ISSUE TITLE
Let's provide a current allocatable capacity of storage volume as an abstract user interface

### ISSUE THREAD

**Issue by lizable** [lablup/backend.ai-webui#1630]
### Main idea

related issue: [backend.ai#1164](https://github.com/lablup/backend.ai/issues/1164)

**Comment by yomybaby** [comment]
Need to change this part :
https://github.com/lablup/backend.ai-webui/blob/fc2abe5db95a9d232b2a24becf56b301f1d12220/src/components/backend-ai-data-view.ts#L367-L374

**Comment by yomybaby** [comment]
[from teams thread](https://teams.microsoft.com/l/message/19:3c0acc0825024daeb2211f55c4e7f4aa@thread.skype/1678937127668?tenantId=13c6a44d-9b52-4b9e-aa34-0513ee7131f2&groupId=74ae2c4d-ec4d-4fdf-b2c2-f5041d1e8631&parentMessageId=1678932275317&teamName=devops&channelName=Backend.AI%20Talks&createdTime=1678937127668&allowXTenantAccess=false)
- When there is only percentage information in item.
  - the WEBUI setting options determine whether to display it as one of three states (green/yellow/red) or as a percentage number.
- When there is also total/used information in the API response,
  - the relevant information is displayed together.
