### ISSUE TITLE
Let's add an option to hide/show `Try preferred port`

### ISSUE THREAD

**Issue by lizable** [lablup/backend.ai-webui#1634]
### Main idea

For now, we've been exposing `Try preferred port` option in app launcher dialog as a default. But some users may not know this option and may use it in a wrong way. Let's add an option to hide/show this feature, as `Open app to public` does.

### Screenshot(s)
<img width="393" alt="Screenshot 2023-03-14 at 7 11 51 PM" src="https://user-images.githubusercontent.com/46954439/224968522-72677411-3029-4583-af9f-aba9fc2de49a.png">

**Comment by lizable** [comment]
@Sujin-Kim1 
Let's implement this by adding show/hide option in the configuration.
Also, since we are encountering flooding options in the configuration, IMHO we shall need a certain naming rule when adding key(s) in the configuration.

**Comment by adrysn** [comment]
For now, I will write a local patch which will be automatically hides the "Try preferred port" by adding styles for the recently added ID for the element (`preferred-app-port-config-box`): https://github.com/lablup/backend.ai-webui/pull/1642/files#diff-8bfdd81f6977f0f8e05c0ba087d666df8c36729464b9b50adad2acba20077326R1140
