### ISSUE TITLE
Session force-terminate button UI is broken

### ISSUE THREAD

**Issue by Sujin-Kim1** [lablup/backend.ai-webui#1679]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### Backend.AI version

22.09.18

### Describe the bug

<img width="151" alt="image" src="https://user-images.githubusercontent.com/28584164/229416738-1051ecc7-ed00-4e83-869d-92d6dcafcef3.png">

### To Reproduce

1. create a new session
2. select session using the checkbox
3. see an error

### Expected Behavior

Force terminate button should be shown in the middle of the tab and grid without a broken layout.
Alternatively, you can relocate the buttons to any location.

**Comment by lizable** [comment]
I think it's because of the styling applied in #1651.
(https://github.com/lablup/backend.ai-webui/blame/main/src/components/backend-ai-session-list.ts#L2728)
Let's remove this style definition.
