### ISSUE TITLE
Let's support UI for vfolder v3

### ISSUE THREAD

**Issue by lizable** [lablup/backend.ai-webui#1712]
### Main idea

Related issue: [backend.ai#1191](https://github.com/lablup/backend.ai/pull/1191)

Since we are going to provide "a new quota model" in order to manage user/project-based quota we need to refactor the corresponding UI for that.

It's surely major change because the architecture has been changed compared to the former version(v2 -> v3),
therefore It's better to split into several phases so that we can serve the essential features ASAP.

```[tasklist]
### 1st Phase
- [ ] #1713
- [ ] https://github.com/lablup/backend.ai-webui/issues/1757
```

```[tasklist]
### 2nd Phase
- [x] ~~default per-storage quota settings~~
- [ ] #1714
- [ ] https://github.com/lablup/backend.ai-webui/issues/1749
```

**Comment by yomybaby** [comment]
I will close this issue even though there are remaining tasks. Any remaining issues will be handled separately on an individual issue.
