### ISSUE TITLE
Add Copy button on sftp dialog

### ISSUE THREAD

**Issue by lizable** [lablup/backend.ai-webui#1730]
### Main idea

IMO, we could add copy button next to cmd area so that user can copy and paste command easily.

<img width="437" alt="MicrosoftTeams-image (55)" src="https://github.com/lablup/backend.ai-webui/assets/46954439/753803d6-5f6c-4c7d-8111-ff7cd77f97a7">

**Comment by mnxmnz** [comment]
Hello, I'm mentee from [2023 OSSCA](https://www.contribution.ac).

This issue is one of the issues recommended to mentees, so I worked with this issue last week.

I noticed that @Sujin-Kim1 assigned to this issue, I left a comment to avoid duplication of work.

I'm sorry for telling you late.

**Comment by Sujin-Kim1** [comment]
Okay. Then I'd like you to write down in detail how to test it in the PR description. Thank you @mnxmnz :)
