### ISSUE TITLE
Request for Real-Time Number Update During Value Manipulation

### ISSUE THREAD

**Issue by jung-min-seo** [lablup/backend.ai-webui#1739]
### Main idea

Would appreciate it if the numbers could also change simultaneously when manipulating values like CPU here.

Noticing that the numbers do not update when manipulating them, leaving me wondering if something is being done incorrectly.

While the numbers do update after releasing the slider, it would be preferable if they also changed in real-time while manipulating it.

**Comment by inureyes** [comment]
@jung-min-seo due to the limitation of slider ( https://github.com/material-components/material-web/tree/mwc/packages/slider#methods ), it is impossible now.
