### ISSUE TITLE
Apply essential user interface for model serving feature to WebUI

### ISSUE THREAD

**Issue by lizable** [lablup/backend.ai-webui#1741]
### Main idea

Related: [backend.ai#1278](https://github.com/lablup/backend.ai/pull/1278)

Backend.AI CLI supports model serving already, so feature we need to implement model serving feature in WebUI as well.
Since model serving is on-going issue, and the volume of the issue is quite big enough to split into several phases, therefore I would like to apply the crucial part first so that we can provide "working" model serving feature.

```[tasklist]
###
- [x] Brainstorming with sketches for "model-serving"
- [ ] https://github.com/lablup/backend.ai-webui/issues/1743
- [ ] https://github.com/lablup/backend.ai-webui/issues/1744
- [ ] https://github.com/lablup/backend.ai-webui/issues/1745
- [ ] https://github.com/lablup/backend.ai-webui/issues/1746
- [ ] trigger custom navigate event from web component to react-router (jongeun)
```

**Comment by lizable** [comment]
Jun 19, 2023 Today's update

Managed to apply new React-based page for model-serving UI.
Now I need to apply two more things, "descriptions" and "modal" to create service.

![Image](https://github.com/lablup/backend.ai-webui/assets/46954439/5d02ce87-8813-47ee-acb8-ea831bcd03b9)

**Comment by yomybaby** [comment]
#1822 handles remain essential features such as sort and filter.
