### ISSUE TITLE
Let's provide UI for pre-opened port in session launcher

### ISSUE THREAD

**Issue by lizable** [lablup/backend.ai-webui#1753]
### Main idea

Let's provide UI for pre-opened port in Session launcher so that the user can use service(s) in the session more freely.
⚠️ Caution: To prevent malicious attempt to open numerous port, we need to add certain key(`maxCountForPreOpenedPort`) to limit max port opening (e.g. using configuration, perhaps?)

**Comment by Sujin-Kim1** [comment]
Progress: add a new pre open button like a environment variable button
<img width="426" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/28584164/c872271f-06dc-49e5-b272-ddb402862ef9">
<img width="421" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/28584164/c3e94a41-c2aa-4b83-ac78-d3878e92aea5">

**Comment by Sujin-Kim1** [comment]
@yomybaby suggested moving both of environment variable config and pre-open ports setting to the inside of `lablup-expansion` and removing the set environment variable list. It's a great idea and I apply it right away. I appreciate it!
