### ISSUE TITLE
Let's review all the functions are working properly in 23.03 version

### ISSUE THREAD

**Issue by lizable** [lablup/backend.ai-webui#1758]
According to [our versioning policy announced in Backend.AI Mono-repo](https://github.com/lablup/backend.ai/blob/main/.github/CONTRIBUTING.md#versioning-scheme), we are facing breaking changes in 23.03 compared to the former version(22.09). I think it's better to check major features not only for new features that are implemented in 23.03 but also for some features that are related to DB migrations(including table split).

If sth isn't working as we expected, then we need to create a hotfix issue and solve it ASAP, before this Wednesday(July 5, 2023.)

```[tasklist]
### Tasks
- [ ] Check new features applied in 23.03 working properly
- [ ] Check existing features working properly
```

**Comment by lizable** [comment]
@yomybaby @Sujin-Kim1 FYI.

**Comment by yomybaby** [comment]
I'm closing this issue because it's stale.
