### ISSUE TITLE
Registry modification button not working

### ISSUE THREAD

**Issue by inureyes** [lablup/backend.ai-webui#1799]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### Backend.AI version

23.09.0 alpha 2

### Describe the bug

<img width="826" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/949915/caf08fcf-2226-4384-8a85-3b144583a2ba">

When pressing registry modification button is pressed, it shows error and dialog does not spawn. After the error, when I click it again, it only shows registry category option, without any other options.

<img width="487" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/949915/6848bdf4-7090-47d5-bc89-8ce4ffd9d2fc">

### To Reproduce

1. Goto `/environment` and choose Registry tab
2. Press gear button.

**Comment by yomybaby** [comment]
this is resolved by https://github.com/lablup/backend.ai-webui/pull/1786
