### ISSUE TITLE
Let's add a button for Backend.AI FastTrack if supported

### ISSUE THREAD

**Issue by lizable** [lablup/backend.ai-webui#1919]
### Main idea

> ⚠️ NOTE: This issue is suggested by customers.

Since tasks in the pipeline created from Backend.AI FastTrack are reflected in sessions in webUI respectively, It's better to provide a single button to access Backend.AI FastTrack site. But This feature is enabled only if they support Backend.AI FastTrack internally.

```[tasklist]
### Tasks
- [ ] https://github.com/lablup/backend.ai-webui/pull/1929
- [ ] https://github.com/lablup/backend.ai/pull/1576
```

**Comment by agatha197** [comment]
I'm having trouble parsing url into json field.
![Image](https://github.com/lablup/backend.ai-webui/assets/28584164/8ac02e91-1e6c-481c-a4d8-c27025514bb9)
