### ISSUE TITLE
Let's add validation to session name of the session launcher

### ISSUE THREAD

**Issue by agatha197** [lablup/backend.ai-webui#1951]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### Backend.AI version

a42c0f1

### Describe the bug

If the user creates a new session with an invalid pattern session name, it causes an input validation error and cannot create a session.
Let's add validation to the session name of the session launcher and prohibit the user to move next progress if the user inputs an invalid session name.

### To Reproduce

Launch a new session launcher with special symbols like #,$,%, etc.

### Expected Behavior

Session name validation is shown and cannot proceed to the next progress.

### Anything else?

The session rename pattern: `^(?:[a-zA-Z0-9][a-zA-Z0-9._-]{2,}[a-zA-Z0-9])?$`
User can't move the next progress with an empty startup command if the session type is `batch`. 
![image](https://github.com/lablup/backend.ai-webui/assets/28584164/7f087733-082c-4ca4-ad68-e90d7045e3c9)

**Comment by adrysn** [comment]
Another feedback from other customers.
