### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by agatha197** [lablup/backend.ai-webui#1959]
### What Operating System(s) are you seeing this problem on?

macOS (Apple Silicon)

### Backend.AI version

23.09

### Describe the bug

When clicking some item from the antd table such as model serving page, it occurs runtime error. 
![image](https://github.com/lablup/backend.ai-webui/assets/28584164/3d674933-4407-4ad1-8f89-fdd75ff6225d)

### To Reproduce

click the serving model from the serving page.

**Comment by inureyes** [comment]
I could not reproduce this. @agatha197  Please check it again.

**Comment by agatha197** [comment]
It is not reproduced. Close the issue.
