### ISSUE TITLE
Displaying folder size in the folder explorer modal.

### ISSUE THREAD

**Issue by agatha197** [lablup/backend.ai-webui#1980]
### What Operating System(s) are you seeing this problem on?

macOS (Apple Silicon)

### Backend.AI version

f6c3964

### Describe the bug

If a user uploads a folder, every folder size in the folder explorer modal is the same. Let's represent it in the correct size of the folder.
![image](https://github.com/lablup/backend.ai-webui/assets/28584164/65559487-f346-45c9-9690-276554da9ae7)

### To Reproduce

Upload any folder using the folder upload feature in the file explorer.

### Expected Behavior

Display folder size.

**Comment by lizable** [comment]
Closing this issue duplicate of #1988.
