### ISSUE TITLE
Hide the size value when filetype is directory in folder explorer

### ISSUE THREAD

**Issue by inureyes** [lablup/backend.ai-webui#1988]
### Main idea

Displaying the size of directory is dependent on host OS, Which may cause confusing situations. For example, it may show the same directory size regardless of the sum of files(including sub-directory) inside the directory. Therefore It's better not to show the size of the file if the file type is directory. Just displaying with -(hyphen) will do.

**Comment by lizable** [comment]
@adrysn suggested adding an option for hiding size of the value when filetype is directory.

**Comment by lizable** [comment]
Duplicates of #1988.
