### ISSUE TITLE
Create AWS-like Filter component

### ISSUE THREAD

**Issue by lizable** [lablup/backend.ai-webui#2027]
Since we've been providing column-based filter in WebUI, which has its own limitation, such as search in general or applying multiple queries in same column, etc.
Therefore by the suggestion of @yomybaby, we would like to enhance filter component as a new component that could:

- [ ] Search by column name (attribute)
- [ ] Search column name (both partially and entirely)
- [ ] Multiple search
- [ ] Search without column (search by value)

This component will take over the former column-based filter.

### Screenshot(s)
- WebUI filter column (based on vaadin-grid)
![Image](https://github.com/lablup/backend.ai-webui/assets/46954439/8abca3c0-ec99-4f74-aed6-4d6d0e694a22)

- AWS filter component
![Image](https://github.com/lablup/backend.ai-webui/assets/46954439/83e20db6-0a98-4149-909a-44aa76303d0f)

**Comment by yomybaby** [comment]
You can see the descriptions below by running `./backend.ai vfolder list --help` 
```
  --filter TEXT     Set the query filter expression.

                    COLUMNS
                        host, name, created_at, creator,
                        ownership_type (USER, GROUP),
                        status (READY, PERFORMING, CLONING, DELETING, MOUNTED),
                        permission (READ_ONLY, READ_WRITE, RW_DELETE, OWNER_PERM)

                    OPERATORS
                        Binary Operators: ==, !=, <, <=, >, >=, is, isnot, like, ilike(case-insensitive), in, contains
                        Condition Operators: &, |
                        Special Symbol: % (wildcard for like and ilike operators)

                    EXAMPLE QUERIES
                        --filter 'status == "READY" & permission in ["READ_ONLY", "READ_WRITE"]'
                        --filter 'created_at >= "2021-01-01" & created_at < "2023-01-01"'
                        --filter 'creator ilike "%@example.com"'

  --order TEXT      Set the query ordering expression.

                    COLUMNS
                        host, name, created_at, creator, ownership_type, status, permission

                    OPTIONS
                        ascending order (default): (+)column_name
                        descending order: -column_name

                    EXAMPLE
                        --order 'host'
                        --order '+host'
                        --order '-created_at'
```

**Comment by lizable** [comment]
I'll make a workaround for search filter component, using search and input UI, instead of AWS-like filter component.

**Comment by yomybaby** [comment]
This issue's requirements are implemented with BAIPropertyFilter and applied to several pages. You can find the related PRs by searching `BAIPropertyFilter`([link](https://github.com/lablup/backend.ai-webui/pulls?q=is%3Apr+is%3Aclosed+BAIPropertyFilter)).

I'll close this issue. Let's handle additional requirements as individual issues if needed.
