### ISSUE TITLE
Feat: Expose endpoint in model serving list

### ISSUE THREAD

**Issue by gee05053** [lablup/backend.ai-webui#2038]
### Main idea

<img width="999" alt="MicrosoftTeams-image" src="https://github.com/lablup/backend.ai-webui/assets/28584221/5056f51d-b3a9-4325-b440-5cdafbf8f7a0">

Add endpoint URL column beside of endpoint ID column
User can see endpoint URL more easily.

**Comment by yomybaby** [comment]
Let's add `created_user` column only for the admin ccount
