### ISSUE TITLE
fix: prevent ModelStoreListPageQuery before 24.03

### ISSUE THREAD

**Issue by yomybaby** [lablup/backend.ai-webui#2073]

**Comment by yomybaby** [comment]
## Reproduce steps
- connect to 23.09.x
- move to `/data` page
- (you can see error below in the develop environment)


![Image](https://github.com/lablup/backend.ai-webui/assets/621215/0573dda7-de1a-4bf1-9df7-c037a00ee63b)

**Comment by agatha197** [comment]
resolved by #2076
