### ISSUE TITLE
Let's disable all of buttons related to updating service in routing info page when service status is in `destroying`

### ISSUE THREAD

**Issue by lizable** [lablup/backend.ai-webui#2075]
### What Operating System(s) are you seeing this problem on?

macOS (Apple Silicon)

### Backend.AI version

24.03.0-alpha.3.5815

### Describe the bug

Since there's a chance to change desired session count on destroying period of service by accessing routing info page and using edit button, or generating token which seems to be useless, I think it's better to disable it.

<img width="967" alt="Screenshot 2023-12-05 at 12 37 06 PM" src="https://github.com/lablup/backend.ai-webui/assets/46954439/eb3f7545-d634-4c7a-b7e7-4901b9b684b7">

### Expected Behavior

After user requested destorying service, user cannot update anything related to the service.

**Comment by lizable** [comment]
Or just disabling link to routing info page would be enough.

**Comment by ironAiken2** [comment]
Resolved via #2200 PR
