### ISSUE TITLE
When creating a session, the name must be checked for validation

### ISSUE THREAD

**Issue by Yaminyam** [lablup/backend.ai-webui#2101]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### Backend.AI version

main

### Describe the bug

![image](https://github.com/lablup/backend.ai-webui/assets/31057849/238b3689-716c-4e5b-abec-137d9c145edc)
When creating a session, the name must be set to 4 to 64 characters.
If this rule is not followed, session creation will fail.
However, in the session creation menu, even if you do not follow the above rules, you will proceed to the next step and an input validation error will occur.
I think it would be a good idea to verify this at the UI level as well so that it cannot proceed to the next step.

**Comment by agatha197** [comment]
duplicated with https://github.com/lablup/backend.ai-webui/issues/1951
