### ISSUE TITLE
fix: apply InputNumberWithSlider and set memory value automatically in ServiceLauncherModal

### ISSUE THREAD

**Issue by gee05053** [lablup/backend.ai-webui#2158]
### Main idea

1. Currently desired routing count is displayed by using SliderInputFormItem at ServiceLauncherModal.
Desired routing count can set maximum 100, but user can increase number infinity.
If InputNumberWithSlider, user can set routing count maximum 100 and can't increase any more.

![스크린샷 2024-01-19 오후 6 53 07](https://github.com/lablup/backend.ai-webui/assets/28584221/1dc90670-9ac3-44d9-b262-72f1bd102d2b)

2. If user change memory unit, memory value is not changed minimum value automatically.
But slider is changed automatically.
![스크린샷 2024-01-19 오후 7 17 20](https://github.com/lablup/backend.ai-webui/assets/28584221/bc1f826f-eca9-447c-a8c5-a3e7b35327fe)

- [ ] Change SliderInputFormItem to InputNumberWithSlider
- [ ] Memory value is changed automatically by unit

**Comment by yomybaby** [comment]
@gee05053 Please update the title more specifically.

**Comment by yomybaby** [comment]
This PR is no longer valid, so I will close it. 👍
