### ISSUE TITLE
The resource allocation values are not saved after refreshing in neo-session.

### ISSUE THREAD

**Issue by agatha197** [lablup/backend.ai-webui#2172]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### Backend.AI version

24.03

### Describe the bug

On the neo-session, we support saving the input values that are used for creating a new session.
But the resource allocation values are not sustained after refreshing.
<img width="712" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/28584164/c54313df-834f-4b51-bd05-0770b88963c4">

### To Reproduce

modify any allocation resources in the neo session and refreshing.

### Expected Behavior

save previous values after refreshing.

**Comment by yomybaby** [comment]
I reopened this issue. It needs to be checked again and handled in the resource preset automation PR(not created yet)

**Comment by yomybaby** [comment]
It resolved already
