### ISSUE TITLE
bug: Tooltip explanning mounted VFolders is not appeared perfectly at NeoSession

### ISSUE THREAD

**Issue by gee05053** [lablup/backend.ai-webui#2191]
### What Operating System(s) are you seeing this problem on?

macOS (Apple Silicon)

### Backend.AI version

24.03.0a1

### Describe the bug

In NeoSession, if mounted Vfolder is too many, Tooptip is appeared to explan what is mounted VFolders.
Howerver after merging React-root, Tooltip is not appeared perfectly like below screenshot.

![스크린샷 2024-01-30 오후 2 47 16](https://github.com/lablup/backend.ai-webui/assets/28584221/a051da21-bcbd-4116-9c05-68e6a7922209)

**Comment by yomybaby** [comment]
This bug is handled in #2220
