### ISSUE TITLE
Bugs: wide tags misshaped in the region column of `/agent` page

### ISSUE THREAD

**Issue by ironAiken2** [lablup/backend.ai-webui#2297]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### Backend.AI version

23.09.10

### Describe the bug

Tags in region columns not displaying correctly.

![Image](https://github.com/lablup/backend.ai-webui/assets/51399982/85aadf8a-a1cb-4660-8687-012e1527e90c)

**Comment by yomybaby** [comment]
If you have a PR related to this, please add a PR to `Development` session as shown below:
<img width="354" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/621215/d1b1092e-78b8-45c7-86c7-94567a4cc328">
Also, I changed the title of this PR to be more clear.
