### ISSUE TITLE
encountered react dependency errors while installing Backend.AI and its webui due to mismatched esbuild version.

### ISSUE THREAD

**Issue by studioego** [lablup/backend.ai-webui#2512]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### Backend.AI version

a50d0f476e9153b9b5e9803b1c804e62f4a956df

### Describe the bug

I created an Ubuntu 22.04 LTS VM on Proxmox. After creating the VM, I encountered the following error while installing Backend.AI and its webui.

It encountered react dependency errors while installing Backend.AI and its webui due to mismatched esbuild version.

Below is installing webui error log.
```shell
[react-dependencies] npm error
[react-dependencies] npm error Error: Expected "0.20.2" but got "0.19.12"
[react-dependencies] npm error     at validateBinaryVersion (/home/bai/backend.ai/src/ai/backend/webui/react/node_modules/esbuild/install.js:133:11)
[react-dependencies] npm error     at /home/bai/backend.ai/src/ai/backend/webui/react/node_modules/esbuild/install.js:286:5
[react-dependencies] npm error
[react-dependencies] npm error Node.js v20.15.0
[react-dependencies]
[react-dependencies] npm error A complete log of this run can be found in: /home/bai/.npm/_logs/2024-07-03T13_04_12_328Z-debug-0.log
[react-dependencies] cd react && npm install exited with code 1
npm error code 1
npm error path /home/bai/backend.ai/src/ai/backend/webui
npm error command failed
npm error command sh -c npx concurrently -c "auto" --names "react-dependencies,patch-package" "cd react && npm install" "patch-package"

npm error A complete log of this run can be found in: /home/bai/.npm/_logs/2024-07-03T13_04_01_528Z-debug-0.log
```
![image](https://github.com/lablup/backend.ai-webui/assets/20002/10fc6e58-6cee-492d-90f5-6e572f4bc145)

I resolved the issue by cleaning the npm cache and reinstalling the dependencies.

```shell
bai@testvm01:~/backend.ai$ rm ./src/ai/backend/webui/package-lock.json
bai@testvm01:~/backend.ai$ cd ./src/ai/backend/webui
bai@testvm01:~/backend.ai/src/ai/backend/webui$ npm i
bai@testvm01:~/backend.ai$ cd ./src/ai/backend/webui/react
bai@testvm01:~/backend.ai/src/ai/backend/webui/react$ npm cache clean --force
bai@testvm01:~/backend.ai/src/ai/backend/webui/react$  rm -rf node_modules package-lock.json
bai@testvm01:~/backend.ai/src/ai/backend/webui/react$ npm install
```

The screenshot shows the successful installation of Backend.AI by running  `install-dev.sh` script after resetting dependencies after deleting the package-lock.json file.
![image](https://github.com/lablup/backend.ai-webui/assets/20002/1ab20740-a515-4ede-b336-eec3579cb269)

### To Reproduce

1. make a new Ubuntu LTS version (I made Ubuntu 22.04 LTS version)
2. install backend.ai dependencies
3. install `install-dev.sh` script 
4. found webui installing error. 

### Expected Behavior

the successful installation of Backend.AI & webui by running  `install-dev.sh` script.
![image](https://github.com/lablup/backend.ai-webui/assets/20002/1ab20740-a515-4ede-b336-eec3579cb269)

**Comment by yomybaby** [comment]
After use `pnpm` https://github.com/lablup/backend.ai-webui/pull/2515 , this issue resolved.
