### ISSUE TITLE
Revoke shared folder permission doesn't working properly

### ISSUE THREAD

**Issue by lizable** [lablup/backend.ai-webui#2545]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### Backend.AI version

24.09.0dev1

### Describe the bug

Revoking the access permission of shared folder from invited user doesn't work properly.

### To Reproduce

> ⚠️ NOTE: You need two user accounts (user A, user B) to test this issue. 

1. Login with user A account.
2. Go to Data & Storage menu.
3. Click `Share folder` icon button(<img width="43" alt="Screenshot 2024-07-12 at 4 04 20 PM" src="https://github.com/user-attachments/assets/0b7b12a5-0e34-479e-a9f2-df29bc4732c6">) in Controls column. 
4. Add user B email address with any permission.
5. Click `SHARE` button.
6. Logout user A account and login with user B account.
7. See invitation panel in Summary page.
8. Accept the invitation.
9. Logout user B account and login with user A account.
10. Go to Data & Storage menu again.
11. Click `Modify Permission` icon button (<img width="43" alt="Screenshot 2024-07-12 at 4 07 08 PM" src="https://github.com/user-attachments/assets/e6c52623-4070-4542-ab60-a713489c9641">) in Controls column.
12. Change the current permission to "kick out user".
13. Logout  user A account and login with user A account.
14. Go to Data & Storage menu.
15. See the error.

### Expected Behavior

When the permission per each shared folder has been changed to "kicked-out", then the invited user shouldn't be able to get access to the shared one.

**Comment by agatha197** [comment]
Already resolved. Close the issue.
