### ISSUE TITLE
Resource policy deletion show delete operation is successfully done even if it failed.

### ISSUE THREAD

**Issue by lizable** [lablup/backend.ai-webui#2546]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### Backend.AI version

24.09.0dev1

### Describe the bug

When one or more user or project is involved in resource policy any user/project resource policy shall not be removed.
But when admin user tries to delete the user/project resource policy the notification shows the operation is successfully done as if deleting request is applied, in fact it's not.

I also checked the GQL result and it shows integration error.

### Screenshot(s)
<img width="788" alt="Screenshot 2024-07-12 at 4 49 40 PM" src="https://github.com/user-attachments/assets/6897958f-1762-485d-b209-99066c8e8d22">
<img width="590" alt="Screenshot 2024-07-12 at 5 28 14 PM" src="https://github.com/user-attachments/assets/e1a3f40b-138d-4f89-aefb-4cb9dd210434">
<img width="590" alt="Screenshot 2024-07-12 at 5 28 25 PM" src="https://github.com/user-attachments/assets/a66d7406-847f-4b26-ae71-967ccc05a748">

### To Reproduce

1. Login with superadmin account.
2. Go to Resource Policy menu.
3. Click User or Project Tab
4. Click trash bin icon button in Control column in one of rows in the table, which contains one or more user account(s).
5. Click delete button in confirmation tooltip.
6. See the error.

### Expected Behavior

If there's any error occurred during the deleting operation, It should be reported to the client.

**Comment by agatha197** [comment]
resolved by #2548
