### ISSUE TITLE
fix:  display the session start time in the session reservation time. Not the session creation time.

### ISSUE THREAD

**Issue by gahyuun** [lablup/backend.ai-webui#2582]
### What Operating System(s) are you seeing this problem on?

macOS (Apple Silicon)

### Backend.AI version

24.03.7

### Describe the bug

In session list page,The session reservation time is displayed as the session creation time. however, the session reservation time should be displayed as the session start time. 

Elapsed time is counted as session creation time but elapsed time should be counted as session start time.

### To Reproduce

display the session start time in the session reservation time. and count as session start time in elapsed time

**Comment by agatha197** [comment]
resolved by #2584
