### ISSUE TITLE
Add delegate-session option in Neo session launcher if current logged in user role is superadmin

### ISSUE THREAD

**Issue by lizable** [lablup/backend.ai-webui#2588]
### Main idea

Since Neo session launcher has been taking the place of Classic session launcher, we need to add the feature that only classic session launcher has; which is execute a delegated-session.

**Comment by yomybaby** [comment]
Resolved by [PR #2693](https://github.com/lablup/backend.ai-webui/pull/2693). Please close this issue and open a new one for the related bug. @lizable
