### ISSUE TITLE
Cannot run any app even though wsproxy set well.

### ISSUE THREAD

**Issue by agatha197** [lablup/backend.ai-webui#2626]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### Backend.AI version

24.03

### Describe the bug

When I try to run any app in the electron mode, I got `Proxy is not ready yet. Check proxy settings for detail.` error. But it is fixed after re-run the backend.ai app.
After that, it was impossible to reproduce, so I couldn't find the cause of this :(

### To Reproduce

1. make a new session in the electron app.
3. run any application.
4. see error.
(But it sometimes occurs, and fixed after re-running the backend.ai app. And I cannot reproduce this error. So if anyone find the reproduce way, feel free to update this issue.)

### Expected Behavior

Run application without error.

**Comment by yomybaby** [comment]
@agatha197 If this is no longer valid, please close the issue.
