### ISSUE TITLE
Resource group doesn't reflect if modifying

### ISSUE THREAD

**Issue by agatha197** [lablup/backend.ai-webui#2770]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### Backend.AI version

24.09.0

### Describe the bug

If users modify a new service, the resource group has different value. Let's modify it so that all values have existing values on the page that comes out when you modify it.

### To Reproduce

1. Make a new service in serving page
2. Modify it
3. Check the resource group is the same as the original one.

**Comment by yomybaby** [comment]
This is resolved by #2774
