### ISSUE TITLE
feat: add missing MEM live stat of accelerators in session list

### ISSUE THREAD

**Issue by yomybaby** [lablup/backend.ai-webui#2801]
Currently, the session list only displays the Mem live stat information of CUDA. Please add the missing MEM live stat of other accelerators.
https://teams.microsoft.com/l/message/19:14c484402d874dafb15806d093b95a82@thread.skype/1730423621006?tenantId=13c6a44d-9b52-4b9e-aa34-0513ee7131f2&groupId=74ae2c4d-ec4d-4fdf-b2c2-f5041d1e8631&parentMessageId=1730271898438&teamName=devops&channelName=Frontend&createdTime=1730423621006

- [Teams thread](https://teams.microsoft.com/l/message/19:14c484402d874dafb15806d093b95a82@thread.skype/1730423621006?tenantId=13c6a44d-9b52-4b9e-aa34-0513ee7131f2&groupId=74ae2c4d-ec4d-4fdf-b2c2-f5041d1e8631&parentMessageId=1730271898438&teamName=devops&channelName=Frontend&createdTime=1730423621006)

**Comment by ironAiken2** [comment]
Resolved via #2802
