### ISSUE TITLE
Remove Unnecessary Pipeline Page Files

### ISSUE THREAD

**Issue by yomybaby** [lablup/backend.ai-webui#2856]
Let's remove the pipeline-related pages as they are no longer used such as `/src/pipeline/*`.
Don't forget to

**Comment by yomybaby** [comment]
@lizable The status of this issue is "Needs review" on the Daily board. If this is correct, please link to the corresponding PR.

**Comment by lizable** [comment]
> [@lizable](https://github.com/lizable) The status of this issue is "Needs review" on the Daily board. If this is correct, please link to the corresponding PR.

Okay, I'll link the PR and mention after I finish E2E testing.
