### ISSUE TITLE
Adding extra input boxes to support the newly added registry types

### ISSUE THREAD

**Issue by jopemachine** [lablup/backend.ai-webui#2914]
### Main idea

Follow-up to #2904.

For the newly added registry types in version 24.09, additional information must be provided via the `extra` JSON string column in the container_registries table.

`extra` data that can be added for each registry type can be checked through the fixtures below.

https://github.com/lablup/backend.ai/tree/main/fixtures/manager

We need to display separate input boxes depending on the registry type, or a simpler solution could be adding an input box to allow users to input the extra data as a JSON string.

#### Github container registries

- `entity_type`: str (`users` or `groups`)

#### Gitlab container registries

- `api_endpoint`: str

#### AWS ECR

- `access_token`: str
- `secret_access_token`: str
- `region`: str (e.g. us-east-1)

**Comment by yomybaby** [comment]
Since additional registry types may be added in the future and the extra data might vary, it would be better to allow direct JSON editing in the WebUI. On the frontend, it would be sufficient to only check for JSON syntax errors.
