### ISSUE TITLE
Cannot upload to vfolder after canceling upload

### ISSUE THREAD

**Issue by adrysn** [lablup/backend.ai-webui#537]
Cannot upload files to a vfolder after canceling file upload. After refreshing the page, it resolves.

How to reproduce:
* Open a file explorer from a vfolder.
* Upload some files.
* Cancel upload.
* Upload other files.
* Upload does not progress.

**Comment by inureyes** [comment]
Worked with first / second trial but failed on third one.

**Comment by Sujin-Kim1** [comment]
Me too. I'll handle it soon.
