### ISSUE TITLE
Allows admin to assign admin rights to other users

### ISSUE THREAD

**Issue by inureyes** [lablup/backend.ai-webui#550]
Following the design strategy, admins cannot activate additional admins. (Supported by Hub.) However, it is necessary to add the corresponding function so that users of the open source version can add admin authority through the GUI.

**Comment by inureyes** [comment]
@Sujin-Kim1  Please check this issue.

**Comment by Sujin-Kim1** [comment]
@inureyes  you mean allow admin? not superadmin? Should I allow the admin to select user roles including other roles such as user, monitor, etc?

**Comment by inureyes** [comment]
@Sujin-Kim1 



Role | Can login? | Change role? | ETC
-- | -- | -- | --
Superadmin | O | Everyone | Only one
Domain admin | O | Under domain | One for domain
Monitor | X | X | Same as domain admin without write
Project owner | O | Under project | Not implemented yet
User | O | X |

**Comment by Sujin-Kim1** [comment]
@inureyes Then is it right to understand properly?
superadmin: it is available to change someone's role to one of domain admin, monitor, project owner, user
domain admin: can change the someone's role to one of project owner, user
project owner: can change the someone's role to project owner

**Comment by Sujin-Kim1** [comment]
We need to add the role change button to webui. Until now, user role changes have only been provided in the control panel.

**Comment by Sujin-Kim1** [comment]
I'm making the modifying modal. And I tried to fill the setting fields with original values, but it displays the previously clicked user's setting. So I struggling with that.

**Comment by Sujin-Kim1** [comment]
TODO:
- [ ] fill input fields with updated data (currently, the previous values are filled after modifying)
- [ ] totp activation setting
