### ISSUE TITLE
Dropdown on session creation dialog shows missing overlay

### ISSUE THREAD

**Issue by inureyes** [lablup/backend.ai-webui#699]
* Dropdown on session creation dialog shows missing overlay
 * See (i) icon.

![imgpsh_mobile_save-1](https://user-images.githubusercontent.com/949915/92079562-10a45200-edfb-11ea-87bc-54ff9d6cc574.jpg)

**Comment by Taewan-P** [comment]
Is this issue still active?
If not, is there a way to reproduce this issue?
**webui**
![webui.png](https://user-images.githubusercontent.com/27392567/125236730-6bfa7700-e31f-11eb-8a30-a76d277fe6a4.png)

**cloud**
![cloud.png](https://user-images.githubusercontent.com/27392567/125236810-8c2a3600-e31f-11eb-91df-da6b0cef26f1.png)

**Comment by lizable** [comment]
@Taewan-P
Recently session launcher dialog has been updated and It seems that this bug was resolved via #1009.
So, @inureyes or @adrysn could double-check and close this issue.
